### ISSUE TITLE
Encoder?

### ISSUE THREAD

**Issue by ghost** [mikesmullin/amf-js#5]
Hello.

This is a very interesting project I must say. It's sad that there's no encoder yet. Will this ever happen? It would be great.

**Comment by mikesmullin** [comment]
Thanks and good question! Honestly, everyone I know is moving _away_ from Adobe Flash technology, so I am surprised to hear you are interested in going backwards. In my case, we were porting a browser-based game from Flash to HTML5 + ES6 + WebGL. So I am curious about your use case.

Currently I have no plans to add an encoder, but a pull request would be welcome. It's not out of scope for the project. I updated the `README.md` to make this clearer to prospective users. Something like JSON-to-AMF would probably not be hard to write. As you can see, the decoder is less than 500 lines, but not all types are supported--since we didn't need them in our case.

**Comment by mikesmullin** [comment]
You may also be interested in this Haxe project [OpenFL](https://github.com/openfl/openfl) which has 2 complete implementations of encoders and decoders to/from AMF.

**Comment by ghost** [comment]
Yes I know, but your implementation is actually pretty nice and I don't really know how to create an encoder for this, that's why I was asking if you could maybe finish it if possible.

**Comment by ghost** [comment]
I've been developing a standalone AMF0 library. If you're interested: https://pastebin.com/dyaDmCJY

**Comment by ghost** [comment]
Well nevermind I guess. I'm creating an AMF0 and AMF3 library. It's currently working very well for me. If you are going to create an encoder I'll see it either way.
